### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mmmurtaza** [Ilmihadiyah1438/likha-likhse#1]
Developing for already popular programs would be a better idea
check this out for google docs
http://googleappsdeveloper.blogspot.in/2014/03/add-ons.html
https://developers.google.com/apps-script/add-ons/

and you'll HAVE TO do something for MS WORD
check this out
http://support.microsoft.com/kb/262605

yours
murtaza

**Comment by abdealikhurrum** [comment]
Thanks, really appreciate the feedback
